### PR TITLE
adding_da_translations

### PR DESCRIPTION
**Pull request by DBC-226**
## Purpose
This is a branch dedicated to providing a Danish translation of BaldPhone.

## Approach
I'm translating bit by bit in my evenings (half an hour here and there) hoping to be able to mark as ready for review in max. two weeks.

#### Open Questions and Pre-Merge TODOs
- [x] Translate some more.
- [x] Ensure common wordings/phrases are identical throughout the translation.

### CODE REVIEW

**Comment by UriahShaulMandel** [comment]
Thanks you so much for the contribution!

**Comment by UriahShaulMandel** [comment]
it didn't compile, please check out the following error message:
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:mergeBaldUpdatesDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource compilation failed
     /home/travis/build/UriahShaulMandel/BaldPhone/app/src/main/res/values-da/strings.xml:19:5-21:14: AAPT: error: unescaped apostrophe in string
         
     /home/travis/build/UriahShaulMandel/BaldPhone/app/src/main/res/values-da/strings.xml:19:5-21:14: AAPT: error: not a valid string.
         
     /home/travis/build/UriahShaulMandel/BaldPhone/app/src/main/res/values-da/strings.xml:83:5-204: AAPT: error: unescaped apostrophe in string
         
     /home/travis/build/UriahShaulMandel/BaldPhone/app/src/main/res/values-da/strings.xml:83:5-204: AAPT: error: not a valid string.
         
     /home/travis/build/UriahShaulMandel/BaldPhone/app/src/main/res/values-da/strings.xml:85:5-151: AAPT: error: unescaped apostrophe in string
         
     /home/travis/build/UriahShaulMandel/BaldPhone/app/src/main/res/values-da/strings.xml:85:5-151: AAPT: error: not a valid string.
         
     /home/travis/build/UriahShaulMandel/BaldPhone/app/src/main/res/values-da/strings.xml:92:5-119: AAPT: error: unescaped apostrophe in string
         
     /home/travis/build/UriahShaulMandel/BaldPhone/app/src/main/res/values-da/strings.xml:92:5-119: AAPT: error: not a valid string.
         
     /home/travis/build/UriahShaulMandel/BaldPhone/app/src/main/res/values-da/strings.xml:251:5-92: AAPT: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
         
     /home/travis/build/UriahShaulMandel/BaldPhone/app/src/main/res/values-da/strings.xml:252:5-98: AAPT: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
         
     /home/travis/build/UriahShaulMandel/BaldPhone/app/src/main/res/values-da/strings.xml:258:5-119: AAPT: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
         
     /home/travis/build/UriahShaulMandel/BaldPhone/app/build/intermediates/incremental/mergeBaldUpdatesDebugResources/merged.dir/values-da/values-da.xml: AAPT: error: file failed to compile.
```

Taken from https://github.com/UriahShaulMandel/BaldPhone/pull/283/checks?check_run_id=904537261

**Comment by UriahShaulMandel** [comment]
Hi @DBC-226 ,
is it finished? can I merge it?
Thanks Again!

**Comment by DBC-226** [comment]
Yes, sorry, but that should be stated in both the commits and why it's marked as ready for review 😁I just figured you were busy, so you would just review when you had the time! On 12 Sep 2020 22.26, Uriah Shaul Mandel <notifications@github.com> wrote:
Hi @DBC-226 ,
is it finished? can I merge it?
Thanks Again!

**Comment by DBC-226** [comment]
Hi @UriahShaulMandel 
Do you think you can merge it? The elderly person I'm helping is _really_ longing for the translation to become available!
Thanks!

**Comment by UriahShaulMandel** [comment]
@DBC-226 Yes,
On it now

**Comment by UriahShaulMandel** [comment]
@DBC-226  it is up! 
you can download it now via Direct APK,
will take more time for it to arrive to F-Droid and Google Play
Please let me know if anything works well!
Uriah

**Pull request merged**
