### PR TITLE
Hindi translation

### PR DESCRIPTION
**Pull request by tarun26091999**
Added the Hindi translation of strings.xml

## Purpose
Hindi translation was missing from the strings folder, so I added the Hindi translation of BaldPhone. Issue - #1042

## Approach
A new value resource file was created in the value folder. Selected Hindi in the language and enabled for all regions .Then all the strings in English are translated into Hindi.

## Usage
Many people do not know English or other languages and they know only Hindi, especially in rural India. So adding the Hindi translation helps the app in reaching to wider audiences. This will help the app grow and more people will be benefited from it.

### CODE REVIEW

**Comment by UriahShaulMandel** [comment]
Thank you so so much for doing it!

**Comment by UriahShaulMandel** [comment]
1 Small thing, you also pushed your own AndroidStudio generated files,
Would you be able to remove them, and make the pull request to translation branch directly?

**Comment by UriahShaulMandel** [comment]
I'm opening a new PR with the same commit instead.

**Comment by tarun26091999** [comment]
@UriahShaulMandel can you please put the link of merged PR in the comment sections here?

**Comment by UriahShaulMandel** [comment]
This PR has been moved to:
https://github.com/UriahShaulMandel/BaldPhone/pull/1044
Thank you so much @tarun26091999

**Pull request closed without merging**
