### PR TITLE
Animation in dialer

### LINKED ISSUE #126: Dialer: When typing a number, the swipe area for recomendations could be extended
**Is your feature request related to a problem? Please describe.**
- When typing a number in dialer and recommendations show at the top, the area  where the swiping is possible is narrow.

**Describe the solution you'd like**
- The area where swipe is accepted, could be increased from the area where the title is (buttons excluded, down to the line where number buttons start, so the area where the typed number is seen, could also act as an swipe area, since it has no purpose but to show a number.

MwvsnkllA0

### PR DESCRIPTION
**Pull request by UriahShaulMandel**
Also fixes #126 and #123 

This is the best solution I can think of, and I think it looks really cool, 
Uploading this Pull Request to hear feedback before I'm publishing
APK for testing can be found here: [BaldPhone - dialer animations TMP.zip](https://github.com/UriahShaulMandel/BaldPhone/files/3882356/BaldPhone.-.dialer.animations.TMP.zip)

dialer_animations

### CODE REVIEW

**Comment by aha999** [comment]
Personally, i don't like that the number pad go up and down by itself, because:
- when i start typing, recommendations pop up and keyboard shrinks and the location of buttons changes, the change of button locations is kinda frustrating.
-when the number i'm typing is saved it's going to stay expanded, but if you get to a point where it's not, it will expand again.
- usually you go to a Phone dial pad to enter a new number, so the expanding/shrinking is kind of annoying.
- i liked it more before because the number pad wasn't transforming when you're typing a number so the location of button didn't change.

- Maybe add a button to the left side of 'add contact', that says 'expand the list' ? idk

That's in my opinion.

I think the static keypad was better.

**Comment by Aokromes** [comment]
Maybe allow change 3 columns 5 rows to 5 columns 3 rows to don't "need" that size change?

**Comment by UriahShaulMandel** [comment]
Ok, I think I understand what you're talking about, and it could actually be really cool!
I'll check how it look, and will post here.
Thanks!

**Comment by RahiAkherajot** [comment]
T9 Keyboard is needed in Dialer

**Pull request closed without merging**
