### PR TITLE
[locale] add Chinese language v1

### PR DESCRIPTION
**Pull request by thomassth**
Overall complete Chinese language pack :)

Some text might look strange to native users, but this is because the strings are set in European language and I can only change so much without asking for restructuring. Absolutely readable though so that can be fixed later.

You can credit me by my github user name

### CODE REVIEW

**Comment by UriahShaulMandel** [comment]
Thank you so much!
Merging, and I'll post an update comment after all tests will pass.
By the way, just interested, how did you hear about BaldPhone?
Thanks Again!

**Comment by thomassth** [comment]
I was looking for a launcher for my grandparents' phones. Took me way too long to find this though. I think I saw your project on Reddit.

**Comment by UriahShaulMandel** [comment]
Cool :) I hope they'll like it.
APK for downloading the app with the translations: [BaldPhone Chinese tmp APK.zip](https://github.com/UriahShaulMandel/BaldPhone/files/3820104/BaldPhone.Chinese.tmp.APK.zip)
After I'll get an OK from you, I'll upload a new version of BaldPhone with the translations
Thanks Again

**Comment by thomassth** [comment]
> Cool :) I hope they'll like it.
> APK for downloading the app with the translations: [BaldPhone Chinese tmp APK.zip](https://github.com/UriahShaulMandel/BaldPhone/files/3820104/BaldPhone.Chinese.tmp.APK.zip)
> After I'll get an OK from you, I'll upload a new version of BaldPhone with the translations
> Thanks Again

I'm not sure why but the translation won't appear. I changed system language to french and the french text appeared just fine, but any Chinese locale still brings up english.

**Comment by UriahShaulMandel** [comment]
Hi, it indeed doesn't work, because of a weird behavior change in Android 7.0+,
https://stackoverflow.com/questions/40543364/can-not-display-chinese-traditional-language-in-android-app
It means the same file will have to be in two different places, so when fixing one the other one should be updated as well. It's weird, but there's not a lot I can do about it :)
Adding the fix and uploading

**Comment by UriahShaulMandel** [comment]
[BaldPhone Chinese tmp APK.zip](https://github.com/UriahShaulMandel/BaldPhone/files/3821317/BaldPhone.Chinese.tmp.APK.zip)
Should hopefully work now :)

**Comment by UriahShaulMandel** [comment]
Hi @thomassth ,
does it work now?

**Pull request merged**
