### PR TITLE
Add support for Swedish

### PR DESCRIPTION
**Pull request by mmFooD**
#1 
Translated the english version of strings.xlm into Swedish. 

I wasn't sure of the context for all of them. But let me know if / when this is applied and I can download the update and have a look and fix any mistakes.

### CODE REVIEW

**Comment by UriahShaulMandel** [comment]
Thank you so much!
Merging now, will add credits later today (not near a computer).
In 20 minutes from now you'll see an automatically generated apk in BaldPhoneCompanion, you can check if the translations are working from there.
Thank you so much again!

**Comment by UriahShaulMandel** [comment]
Also, what name should I put in the credits?

**Comment by mmFooD** [comment]
My name is Patrik Bogren. 

I noticed some strings that should be fixed, I'll add a PR in the coming days...

Great work with the app!

**Comment by UriahShaulMandel** [comment]
Thanks Patrik!
Will add credits tommorow.

**Pull request merged**
